### PR TITLE
Preserve bc, de, hl, ix when closing filestreams in write mode

### PR DESCRIPTION
**Pull request by unlimitedbacon**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Looks like a pretty big change. I'll have to test it out before I merge this.

**Comment by unlimitedbacon** [comment]
It only looks big because of the indents. Really I just added some pushes and pops, but testing is always good.

**Comment by SirCmpwn** [comment]
Alright, I'll poke around in a few minutes and give this a merge.

**Comment by unlimitedbacon** [comment]
If you want to just fix it yourself and keep the git blames, I'm cool with that. I kinda wish git had a better way of handling just whitespace changes.

**Comment by SirCmpwn** [comment]
Nah, I just haven't had a spare moment to review this more closely. I'll merge it, sorry for the wait.

**Comment by unlimitedbacon** [comment]
No rush

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
