### PR TITLE
IO support in kernel

### PR DESCRIPTION
**Pull request by matrefeytontias**
Do not merge this before everything is checked:

- Implement reception
  - [x] On link assist-enabled calcs
  - [ ] On other calcs
  - [ ] From PC
- Implement send
  - [x] On link assist-enabled calcs
  - [ ] On other calcs
  - [ ] To PC

### CODE REVIEW

**Comment by SirCmpwn** [comment]
How's it coming, @matrefeytontias?

**Comment by matrefeytontias** [comment]
Unfortunately, school is winning its fight against programming. I'll try to take some time from other projects to dedicate to this.

**Comment by matrefeytontias** [comment]
While I'm at it I'll resolve some merge conflicts.

**Comment by SirCmpwn** [comment]
:smile: 

No need to spend more time on it than you can afford to, I was just curious.

**Comment by matrefeytontias** [comment]
Implemented send on link assist-enabled calcs with d87c91e7e6761ce0528701e94b525bf72e0dfb9c.

**Comment by SirCmpwn** [comment]
Woot woot! So now we can send and receive on 15 MHz calcs, right?

**Comment by matrefeytontias** [comment]
Yep, exactly.

**Comment by SirCmpwn** [comment]
Awesome!

**Comment by SirCmpwn** [comment]
Experimented a bit with this branch. Two issues:

1. Receiving OS upgrades does not work with this kernel
2. Without the calls to sleep, [this code](https://gist.github.com/SirCmpwn/2294140375dc7f883e0e) crashes the calc (and wabbitemu)
3. Without a second calc connected, that code will crash when you press a key twice
4. The same code shows you the keys *you've* pressed, which leads me to believe that it's receiving its own frames? The other calc never gets frames.

**Comment by SirCmpwn** [comment]
Tested with a TI-84+ and TI-84+ SE.

**Pull request closed without merging**
