### PR TITLE
Add createSymLink

### PR DESCRIPTION
**Pull request by unlimitedbacon**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Nice!

**Comment by SirCmpwn** [comment]
Can you add the entry to the end of the jump table so we don't have to recompile the entire userspace to merge this?

Testing it now, rest of the code looks good.

**Comment by SirCmpwn** [comment]
Nevermind on the jump table thing, I didn't read enough context on the diff.

**Comment by SirCmpwn** [comment]
Testing looks good, nice work!

**Comment by unlimitedbacon** [comment]
Excellent

**Comment by SirCmpwn** [comment]
With this in place, we can finish the castle (1.0.0).

**Pull request merged**
